### ISSUE TITLE
Dragging Files

### ISSUE THREAD

**Issue by Jutarokun** [technerium/obsidian-ukiyo#1]
Hey
I have a problem when dragging my files somewhere in the tree. It lags behind and is just really slow.
Changed the theme to see if it was an issue with that and the behavior changed, so it has to come from the theme.

**Comment by MERJIndustries** [comment]
Hey, this is still an ongoing issue to this day I have a temporary work around for anyone who comes across this issue and enjoys this theme. I did some messing around, not sure if its essential code lol but it seems to work as a temp fix?

```css
/* Major lag causers */
.nav-files-container *,
.tree-item,
.tree-item-self {
    transition: none !important;
    animation: none !important;  /* Add this line if lag still continues */
}

/* Add this section if lag still still continues */
.nav-file-title,
.nav-folder-title {
    transition: none !important;
    animation: none !important;  /* Add this line if lag still still still continues */
}

/* If lag still persists, may god help you */
```
(Its not perfect)
